Repository MIT-Emerging-Talent/ET6-foundations-group-08, pull requests merged in 2025-01, with the labels that each got.

#18 tools of collaborative development assignment
  solutions/Tools of Collaborative Development.md
Labels: assignment

#20 fix config error
  .vscode/settings.json
Labels: bug

#35 this commit will update our solution folder with the tools of collabo…
  solutions/tools_of_collaboration_team_nexus_assignment
Labels: assignment

#36 fix name
  solutions/tools_of_collaboration_assignment_team_nexus.md
Labels: assignment

#30 'Game Of Life' implementation in python with tkinter.
  solutions/game_of_life/README.md
  solutions/game_of_life/game_of_life.py
  solutions/game_of_life/test_game_of_life.py
  solutions/tools_of_collaborative_developement.md
Labels: challenge

#40 Find the maximum of two numbers
  solutions/find_the_maximum_of_two_numbers.py
  solutions/tests/test_find_the_maximum_of_two_numbers.py
Labels: challenge

#46 Find the largest number
  solutions/check_even_or_odd.py
  solutions/find_largest_number.py
  solutions/tools_of_collaboration_assignment_team_nexus.md
  solutions/tools_of_collaborative_developement.md
  tools_of_collaborative_development.md
Labels: challenge

#44 Merge two given list
  solutions/find_the_maximum_of_two_numbers.py
  solutions/merge_two_given_lists.py
  solutions/tests/test_find_the_maximum_of_two_numbers.py
  solutions/tests/test_merge_two_given_lists.py
Labels: challenge, discussion

#47 Reverse a String new Code
  solutions/6-reverse-a-string.py
  solutions/tests/test 6-reverse-a-string.py
Labels: challenge

#55 please review this one
  solutions/check_if_a_number_is_even_or_odd
Labels: challenge

#56 add retrospective.md
  collaboration/retrospective.md
Labels: documentation
